name = "retailfluencer"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "retailfluencer-db"
database_id = "728d9d28-d7d1-450a-ae14-bd147ecf49d1"

# [vars]
# ENVIRONMENT = "production"

# [[kv_namespaces]]
# binding = "CACHE"
# id = "YOUR_KV_ID"
